"""
Retry configuration.
"""

RETRY_CONFIG = {
    "HTTP_MAX_RETRIES": 3,
    "HTTP_BASE_DELAY": 2.0,
    "HTTP_MAX_DELAY": 60.0,
    "HTTP_BACKOFF_FACTOR": 2.0,
    "SUBPROCESS_MAX_RETRIES": 5,
    "SUBPROCESS_BASE_DELAY": 2.0,
    "SUBPROCESS_MAX_DELAY": 60.0,
    "SUBPROCESS_MAX_TOTAL_TIME": 1800,
    "SUBPROCESS_TIMEOUT": 600,
}
