"""
Core module for Odysseus.
Contains configuration, exceptions, logging setup, and validation.
"""

from .config import (
    ACOUSTID_CONFIG,
    APPLE_MUSIC_CONFIG,
    BASE_DIR,
    CACHE_CONFIG,
    CONFIG_DIR,
    DISCOGS_CONFIG,
    DOWNLOAD_CONFIG,
    DOWNLOADS_DIR,
    DURATION_VALIDATION_THRESHOLDS,
    ERROR_MESSAGES,
    LOGGING_CONFIG,
    MUSICBRAINZ_CONFIG,
    PROJECT_DESCRIPTION,
    PROJECT_DOWNLOADS_DIR,
    PROJECT_NAME,
    PROJECT_ROOT,
    PROJECT_VERSION,
    RETRY_CONFIG,
    VALIDATION_RULES,
    YOUTUBE_CONFIG,
)
from .exceptions import (
    APIError,
    ConfigurationError,
    DownloadError,
    MetadataError,
    NetworkError,
    OdysseusError,
    SearchError,
    ValidationError,
)
from .logger import get_logger, setup_logging
from .validation import check_dependencies, validate_and_raise, validate_configuration

__all__ = [
    "ACOUSTID_CONFIG",
    "APIError",
    "APPLE_MUSIC_CONFIG",
    "BASE_DIR",
    "CACHE_CONFIG",
    "CONFIG_DIR",
    "ConfigurationError",
    "DISCOGS_CONFIG",
    "DOWNLOAD_CONFIG",
    "DOWNLOADS_DIR",
    "DURATION_VALIDATION_THRESHOLDS",
    "DownloadError",
    "ERROR_MESSAGES",
    "LOGGING_CONFIG",
    "MUSICBRAINZ_CONFIG",
    "MetadataError",
    "NetworkError",
    "OdysseusError",
    "PROJECT_DESCRIPTION",
    "PROJECT_DOWNLOADS_DIR",
    "PROJECT_NAME",
    "PROJECT_ROOT",
    "PROJECT_VERSION",
    "RETRY_CONFIG",
    "SearchError",
    "VALIDATION_RULES",
    "ValidationError",
    "YOUTUBE_CONFIG",
    "check_dependencies",
    "get_logger",
    "setup_logging",
    "validate_and_raise",
    "validate_configuration",
]
